services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - 5460:5432
    volumes:
      - db-library-data:/var/lib/postgresql/data

volumes:
  db-library-data:
